### ISSUE TITLE
Buffered metrics are not sent on shutdown

### ISSUE THREAD

**Issue by despegargcampelo** [despegar/khronus-java-client#5]
When the client is shutdown(https://github.com/despegar/khronus-java-client/blob/master/src/main/java/com/despegar/khronus/jclient/buffer/BoundedBuffer.java#L100), it does not check if there are any metrics left in the buffer, therefore they are lost

**Comment by dpsoft** [comment]
related to https://github.com/despegar/khronus-java-client/pull/6
